package es.microforum.model;

// Generated 13-ene-2014 19:51:49 by Hibernate Tools 4.0.0

/**
 * Empleado generated by hbm2java
 */

@Entity
@Table(name = "empleado")
public class Empleado implements java.io.Serializable {

	private String dni;
	private Integer version;
	private Empresa empresa;
	private String nombre;
	private String direccion;
	private String tipoEmpleado;
	private String empleadocol;
	private Double salarioAnual;
	private Double valorHora;
	private Double cantidadHoras;
	private byte[] imagen;

	public Empleado() {
	}

	public Empleado(String dni) {
		this.dni = dni;
	}

	public Empleado(String dni, Empresa empresa, String nombre,
			String direccion, String tipoEmpleado, String empleadocol,
			Double salarioAnual, Double valorHora, Double cantidadHoras,
			byte[] imagen) {
		this.dni = dni;
		this.empresa = empresa;
		this.nombre = nombre;
		this.direccion = direccion;
		this.tipoEmpleado = tipoEmpleado;
		this.empleadocol = empleadocol;
		this.salarioAnual = salarioAnual;
		this.valorHora = valorHora;
		this.cantidadHoras = cantidadHoras;
		this.imagen = imagen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dni")
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "empresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "tipoEmpleado")
	public String getTipoEmpleado() {
		return this.tipoEmpleado;
	}

	public void setTipoEmpleado(String tipoEmpleado) {
		this.tipoEmpleado = tipoEmpleado;
	}

	@Column(name = "empleadocol")
	public String getEmpleadocol() {
		return this.empleadocol;
	}

	public void setEmpleadocol(String empleadocol) {
		this.empleadocol = empleadocol;
	}

	@Column(name = "salarioAnual")
	public Double getSalarioAnual() {
		return this.salarioAnual;
	}

	public void setSalarioAnual(Double salarioAnual) {
		this.salarioAnual = salarioAnual;
	}

	@Column(name = "valorHora")
	public Double getValorHora() {
		return this.valorHora;
	}

	public void setValorHora(Double valorHora) {
		this.valorHora = valorHora;
	}

	@Column(name = "cantidadHoras")
	public Double getCantidadHoras() {
		return this.cantidadHoras;
	}

	public void setCantidadHoras(Double cantidadHoras) {
		this.cantidadHoras = cantidadHoras;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

}
